source 'https://rubygems.org'
gem 'maruku'
gem 'sinatra'
gem 'mongo'
gem 'bson_ext'
gem 'oauth2'
gem 'json'
gem 'haml'
gem 'psych', '0.0.0', git: 'git://github.com/tenderlove/psych.git'

gem 'shotgun'
